### ISSUE TITLE
No "extract_icdar_output" function in ocrpostcorrection.token_classification

### ISSUE THREAD

**Issue by Bo-Feng-1024** [jvdzwaan/ocrpostcorrection-notebooks#1]
Hi jvdzwaan, 

In the "icdar-create-hf-dataset.ipynb" the part of "Create 'perfect' icdar output", `from ocrpostcorrection.token_classification import extract_icdar_output`, there is no `extract_icdar_output` in `token_classification.py`. How to fix this problem? Also, what is the "Create 'perfect' icdar output" part for?

Thank you!

**Comment by Bo-Feng-1024** [comment]
Also, in the line of `!python ../evalTool_ICDAR2017.py ../../../data/ICDAR2019_POCR_competition_dataset/ICDAR2019_POCR_competition_evaluation_4M_without_Finnish {out_json} {out_csv}`, there is no function called `evalTool_ICDAR2017.py `.

**Comment by jvdzwaan** [comment]
Hi Bo-Feng,

`from ocrpostcorrection.token_classification import extract_icdar_output` should be `from ocrpostcorrection.utils import extract_icdar_output`. I guess I used the code in the `icdar-create-hf-dataset.ipynb` to make the `create_perfect_icdar_output` function (also in `ocrpostcorrection.utils`). 

'Perfect icdar output` is basically a mapping from all ocr mistakes in the icdar data to their correction. The idea is to use 'perfect icdar output' as input for error correction (task 2), to be able to evaluate the performance of the error correction model separately (instead of evaluating performance for error detection and correction simultaneously). This work is still in progress :)

You are correct that there is no module `evalTool_ICDAR2017.py` anymore. I have added the evaluation function to `ocrpostcorrection.utils` (see also: https://jvdzwaan.github.io/ocrpostcorrection/utils.html#running-the-icdar-evaluation-script). To run the evaluation function, you can use `runEvaluation` (from `ocrpostcorrection.utils`). (I also changed the code of the evaluation function a bit, because there was a bug in it).

I have updated the notebook.

**Comment by Bo-Feng-1024** [comment]
Thank you very much!
